version: '3.9'
services:
  jenkins-docker:
    command:
      - --storage-driver
      - overlay2
    container_name: jenkins-docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker
    ports:
    - 2376:2376
    privileged: true
    volumes:
    - /jenkins-docker-certs:/certs/client
    - /jenkins-data:/var/jenkins_home

networks:
  jenkins:
